robot_params = struct(  'm',4.036, ...
                        'I',0.09, ...
                        'R',0.1, ...
                        'alpha_b',0.3, ...
                        'alpha_w',0.15, ...
                        'dt',0.1, ...
                        'v_max',2, ...
                        'om_max',0.5, ...
                        'K_F',1, ...
                        'K_M',1 ...
                        );
